### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by theamazing0** [Picocrypt/Picocrypt#56]
The Linux (installed with Flatpak) doesn't seem to support Wayland. I have tried disabling X with Flatpak's permission manager and enabling Wayland, but it just causes Picocrypt to crash.

```
flatpak run io.github.picocrypt.Picocrypt
2024/09/13 18:43:30 PlatformError: X11: The DISPLAY environment variable is missing
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/Picocrypt/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x10004?})
        /run/build/picocrypt-gui/vendor/github.com/Picocrypt/glfw/v3.3/glfw/error.go:174 +0x22f
github.com/Picocrypt/glfw/v3.3/glfw.panicError(...)
        /run/build/picocrypt-gui/vendor/github.com/Picocrypt/glfw/v3.3/glfw/error.go:185
github.com/Picocrypt/glfw/v3.3/glfw.WindowHint(0x1f01f840?, 0x1f01f840?)
        /run/build/picocrypt-gui/vendor/github.com/Picocrypt/glfw/v3.3/glfw/window.go:275 +0x34
github.com/Picocrypt/imgui-go.NewGLFW({0x1f01a0e8?}, {0x82b80e, 0x9}, 0x13e, 0x1fb, 0x1)
        /run/build/picocrypt-gui/vendor/github.com/Picocrypt/imgui-go/PlatformGlfw.go:68 +0xa5
github.com/Picocrypt/giu.NewMasterWindow({0x82b80e, 0x9}, 0x13e, 0x1fb, 0x1)
        /run/build/picocrypt-gui/vendor/github.com/Picocrypt/giu/MasterWindow.go:73 +0x285
main.main()
        /run/build/picocrypt-gui/Picocrypt.go:2335 +0x32
```

**Comment by theamazing0** [comment]
Read through #18, this seems to be the reason:

```
The gl/glfw version in the current giu is X only, so adding Wayland won't do anything. If we figure out Wayland in the future, it can always be added in.
```

**Comment by Retengart** [comment]
I tried this on the default GNOME Wayland session, it seems to me that everything is fine even with --socket=x11. 
Maybe you can try to check on --socket=wayland and --socket=fallback-x11 instead of default --socket=x11 for Picocrypt. 
Use [Flatseal ](https://flathub.org/apps/com.github.tchx84.Flatseal) to change permissions

**Comment by theamazing0** [comment]
That's interesting, I'm also on GNOME Wayland and that's what I tried. Here are the permissions I gave Picocrypt: 
![image](https://github.com/user-attachments/assets/1a3f3fac-e475-452e-9ba4-385e9ab36f0b)

**Comment by Retengart** [comment]
Try to leave only second and third permission

**Comment by theamazing0** [comment]
Yes, have tried that as well, same error occurs.

**Comment by Retengart** [comment]
And what about the default single Picocrypt executable?
https://github.com/Picocrypt/Picocrypt/releases/download/1.43/Picocrypt

**Comment by theamazing0** [comment]
It seems to be running with XWayland. Xeyes is an application that relies on an X server (doesn't work on wayland) and makes the eyes follow the cursor. The eyes are following the cursor when the cursor is on the Picocrypt window.

![image](https://github.com/user-attachments/assets/e193318d-860a-4618-8db7-27c52936cbb4)

**Comment by theamazing0** [comment]
Do you have a similar issue when running without XWayland, or does it seem to be working fine on Wayland?

**Comment by Retengart** [comment]
I am not the Wayland user though, usually "dwell" on Void Linux with XFCE. I've tried Picocrypt's normal cases on CachyOS with GNOME (Wayland) with XWayland. Apparently, XWayland is still a panacea.

**Comment by theamazing0** [comment]
Oh I see, yeah since it works well under XWayland this isn't a critical issue. However, due to the security advantages, direct Wayland support would be nice in the future.

**Comment by HACKERALERT** [comment]
Closing as part of a cleanup effort. If XWayland ceases to exist, feel free to reopen.
